print("The integer equivalents of B is", ord('B'))
print("The integer equivalents of C is", ord('C'))
print("The integer equivalents of D is", ord('D'))
print("The integer equivalents of b is", ord('b'))
print("The integer equivalents of c is", ord('c'))
print("The integer equivalents of d is", ord('d'))
print("The integer equivalents of 0 is", ord('0'))
print("The integer equivalents of 1 is", ord('1'))
print("The integer equivalents of 2 is", ord('2'))
print("The integer equivalents of $ is", ord('$'))
print("The integer equivalents of * is", ord('*'))
print("The integer equivalents of + is", ord('+'))
print("The integer equivalents of space is", ord(' '))
